### ISSUE TITLE
Exception: "arrow" module is not available

### ISSUE THREAD

**Issue by glensc** [fuzeman/trakt-tools#5]
```
$ trakt_tools history:duplicates:merge
```

```
...
Scanning for duplicates...
 - Processing 1000 items... (page 1 of 3)
Traceback (most recent call last):
  File "/home/glen/.local/bin/trakt_tools", line 8, in <module>
    sys.exit(main())
  File "/home/glen/.local/lib/python2.7/site-packages/trakt_tools/runner/main.py", line 58, in main
    cli(prog_name=get_prog(), obj={}, max_content_width=100)
  File "/home/glen/.local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/glen/.local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/glen/.local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/glen/.local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/glen/.local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/glen/.local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/glen/.local/lib/python2.7/site-packages/trakt_tools/runner/commands/history/duplicates/merge.py", line 73, in history_duplicates_merge
    review=review
  File "/home/glen/.local/lib/python2.7/site-packages/trakt_tools/tasks/history/duplicates/merge/main.py", line 36, in run
    review=review
  File "/home/glen/.local/lib/python2.7/site-packages/trakt_tools/tasks/history/duplicates/merge/main.py", line 81, in process
    if not self.scanner.scan(profile):
  File "/home/glen/.local/lib/python2.7/site-packages/trakt_tools/tasks/history/duplicates/scan/main.py", line 98, in scan
    if not self.process_item(item):
  File "/home/glen/.local/lib/python2.7/site-packages/trakt_tools/tasks/history/duplicates/scan/main.py", line 120, in process_item
    return self.map_item(self._current_movies, SyncMapper.movie(None, None, data))
  File "/home/glen/.local/lib/python2.7/site-packages/trakt/mapper/sync.py", line 35, in movie
    movie._update(item)
  File "/home/glen/.local/lib/python2.7/site-packages/trakt/objects/movie.py", line 80, in _update
    super(Movie, self)._update(info, **kwargs)
  File "/home/glen/.local/lib/python2.7/site-packages/trakt/objects/video.py", line 96, in _update
    self.watched_at = from_iso8601(info.get('watched_at'))
  File "/home/glen/.local/lib/python2.7/site-packages/trakt/core/helpers.py", line 90, in from_iso8601
    raise Exception('"arrow" module is not available')
Exception: "arrow" module is not available
```

**Comment by glensc** [comment]
installing from pip, did not help. error is still there:

```
$ pip install arrow
DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: arrow in /home/glen/.local/lib/python2.7/site-packages (0.15.5)
Requirement already satisfied: python-dateutil in /usr/local/lib/python2.7/dist-packages (from arrow) (2.8.1)
Requirement already satisfied: backports.functools-lru-cache>=1.2.1; python_version == "2.7" in /usr/local/lib/python2.7/dist-packages (from arrow) (1.6.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python2.7/dist-packages (from python-dateutil->arrow) (1.14.0)

$
```

**Comment by glensc** [comment]
however re-install with pip3 helped!

**Comment by fuzeman** [comment]
I'll close this issue as it appears you have it working now with Python 3.

-----------

If anyone else has this issue, running this command would help me diagnose the issue:
```
python -c "import arrow; print(arrow)"
```
